services:
  cv:
    image: node:latest
    container_name: cv
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    ports:
      - "5173:5173"
